CREATE TABLE EMP (
  empno NUMBER(4) NOT NULL PRIMARY KEY,
  ename VARCHAR2(10),
  job VARCHAR2(10),
  mgr NUMBER(4),
  hiredate DATE,
  sal NUMBER(7, 2),
  comm NUMBER(7, 2),
  deptno NUMBER(2) NOT NULL
);
DESCRIBE EMP;

CREATE TABLE EMP_PART AS SELECT empno, ename, job, sal, comm FROM EMP;
DESCRIBE EMP_PART;
DROP TABLE EMP_PART;

ALTER TABLE EMP ADD (spouses_name CHAR(10));
DESCRIBE EMP;

ALTER TABLE EMP MODIFY (ename VARCHAR2(12));
DESCRIBE EMP;

CREATE TABLE CUSTOMER(
  last_name VARCHAR2(30) NOT NULL,
  state_cd VARCHAR(2),
  sales NUMBER(4)
);

CREATE TABLE STATE(
  state_id VARCHAR(2) NOT NULL,
  state_name VARCHAR2(30)
);
