CREATE VIEW d10emp AS
SELECT empno, ename, sal FROM EMP WHERE deptno = 10;
SELECT * FROM d10emp;
DROP VIEW d10emp;

CREATE INDEX i_ename ON EMP(ename);
CREATE UNIQUE INDEX i_empno ON EMP(empno);

SELECT ename, job, sal FROM EMP;
SELECT * FROM EMP WHERE ename = 'jones';

DROP INDEX i_ename;

CREATE USER myself IDENTIFIED BY my;
ALTER USER myself IDENTIFIED BY me；

GRANT SELECT ON DEPT TO myself;
GRANT SELECT ON EMP TO PUBLIC;

REVOKE ALL ON DEPT FROM myself；
REVOKE SELECT ON EMP  FROM PUBLIC;

DROP USER myself;
