CREATE TABLE DEPT (
  deptno NUMBER(2) NOT NULL PRIMARY KEY,
  dname VARCHAR2(20)
);
DESCRIBE DEPT;

CREATE TABLE EMP (
  empno NUMBER(4) NOT NULL PRIMARY KEY,
  ename VARCHAR2(10),
  job VARCHAR2(10),
  mgr NUMBER(4),
  hiredate DATE,
  sal NUMBER(7, 2),
  comm NUMBER(7, 2),
  deptno NUMBER(2) NOT NULL,
  FOREIGN KEY (deptno) REFERENCES DEPT(deptno)
);
DESCRIBE EMP;
ALTER TABLE EMP ADD (spouses_name CHAR(10));
DESCRIBE EMP;
ALTER TABLE EMP MODIFY (ename VARCHAR2(12));
DESCRIBE EMP;

CREATE TABLE EMP_PART AS SELECT empno, ename, job, sal, comm FROM EMP;
DESCRIBE EMP_PART;
DROP TABLE EMP_PART;

CREATE TABLE STATE(
  state_id VARCHAR(2) NOT NULL,
  state_name VARCHAR2(30),
  PRIMARY KEY (state_id)
);
DESCRIBE STATE;

CREATE TABLE CUSTOMER(
  last_name VARCHAR2(30) NOT NULL,
  state_id VARCHAR(2),
  sales NUMBER(4),
  FOREIGN KEY (state_id) REFERENCES STATE(state_id)
);
DESCRIBE CUSTOMER;

CREATE TABLE PROJECTS (
  projid NUMBER(4) NOT NULL PRIMARY KEY,
  p_desc VARCHAR2(20),
  p_start_date DATE,
  p_end_date DATE,
  budget_amount NUMBER(7, 2),
  max_no_staff NUMBER(2),
  CONSTRAINT check_date CHECK (p_start_date < p_end_date)
);
DESCRIBE PROJECTS;
ALTER TABLE PROJECTS ADD (comments LONG);
DESCRIBE PROJECTS;

CREATE TABLE ASSIGNMENTS (
  projid NUMBER(4) NOT NULL,
  empno NUMBER(4) NOT NULL,
  a_start_date DATE,
  a_end_date DATE,
  bill_rate NUMBER(4, 2),
  assign_type VARCHAR2(2),
  FOREIGN KEY(projid) REFERENCES PROJECTS(projid),
  FOREIGN KEY(empno) REFERENCES EMP(empno)
);
DESCRIBE ASSIGNMENTS;
ALTER TABLE ASSIGNMENTS ADD (hours NUMBER);
DESCRIBE ASSIGNMENTS;

CREATE TABLE S (
  s# VARCHAR2(8) NOT NULL PRIMARY KEY,
  sname VARCHAR2(20),
  age NUMBER(2),
  sex VARCHAR2(6)
);
DESCRIBE S;

CREATE TABLE C (
  c# VARCHAR2(8) NOT NULL PRIMARY KEY,
  cname VARCHAR2(20),
  teacher VARCHAR2(20)
);
DESCRIBE C;

CREATE TABLE SC (
  s# VARCHAR2(8),
  c# VARCHAR2(8),
  grade NUMBER(3),
  PRIMARY KEY(s#, c#),
  FOREIGN KEY(s#) REFERENCES S(s#),
  FOREIGN KEY(c#) REFERENCES C(c#)
);
DESCRIBE SC;
