DROP DATABASE IF EXISTS Words;
CREATE DATABASE Words CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';
USE Words;

CREATE TABLE Word (
    word VARCHAR(255) NOT NULL,
    len INT NOT NULL,
    PRIMARY KEY(word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Target (
    word VARCHAR(255) NOT NULL,
    len INT NOT NULL,
    PRIMARY KEY(word)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
