# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('cno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('cdept', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'C',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('sno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=8)),
                ('age', models.IntegerField()),
                ('sdept', models.CharField(max_length=255)),
                ('pswd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'S',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('tno', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=255)),
                ('tdept', models.CharField(max_length=255)),
                ('pswd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'T',
                'managed': False,
            },
        ),
    ]
