# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Colleges',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Opencourses',
            fields=[
                ('semester', models.CharField(max_length=255, primary_key=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='courseSelection.Courses')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='courseSelection.Teachers')),
                ('class_time', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rated', models.IntegerField(blank=True, null=True)),
                ('num_of_student', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OpenCourses',
            },
        ),
        migrations.CreateModel(
            name='Sc',
            fields=[
                ('sc_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sc_semester', to='courseSelection.Opencourses')),
                ('SCcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sc_courses', to='courseSelection.Opencourses')),
                ('SCteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sc_teacher', to='courseSelection.Opencourses')),
                ('sc_class_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sc_class_time', to='courseSelection.Opencourses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courseSelection.Students')),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SC',
            },
        ),
        migrations.AddField(
            model_name='teachers',
            name='college_name',
            field=models.ForeignKey(db_column='college_name', on_delete=django.db.models.deletion.CASCADE, to='courseSelection.Colleges'),
        ),
        migrations.AddField(
            model_name='students',
            name='college_name',
            field=models.ForeignKey(blank=True, db_column='college_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='courseSelection.Colleges'),
        ),
        migrations.AddField(
            model_name='courses',
            name='college_name',
            field=models.ForeignKey(blank=True, db_column='college_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='courseSelection.Colleges'),
        ),
        migrations.AlterUniqueTogether(
            name='sc',
            unique_together=set([('sc_semester', 'SCcourse', 'SCteacher', 'sc_class_time', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='opencourses',
            unique_together=set([('semester', 'course', 'teacher', 'class_time')]),
        ),
    ]
