DROP DATABASE IF EXISTS xk;
CREATE DATABASE xk CHARACTER SET 'utf8' COLLATE 'utf8_general_ci';
USE xk;

CREATE TABLE S (
    sno CHAR(8) NOT NULL,
    sname VARCHAR(255) NOT NULL,
    gender VARCHAR(8) NOT NULL DEFAULT 'Male',
    age INTEGER NOT NULL,
    sdept VARCHAR(255) NOT NULL,
    pswd VARCHAR(255) NOT NULL,

    PRIMARY KEY(sno)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE T (
    tno CHAR(8) NOT NULL,
    tname VARCHAR(255) NOT NULL,
    tdept VARCHAR(255) NOT NULL,
    pswd VARCHAR(255) NOT NULL,

    PRIMARY KEY(tno)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE C (
    cno CHAR(8) NOT NULL,
    cname VARCHAR(255) NOT NULL,
    credit INTEGER NOT NULL,
    cdept VARCHAR(255) NOT NULL,
    tno CHAR(8) NOT NULL,

    PRIMARY KEY(cno),
    FOREIGN KEY(tno) REFERENCES T(tno) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SC (
    id CHAR(8),
    sno CHAR(8),
    cno CHAR(8),
    grade INTEGER,

    PRIMARY KEY(id),
    FOREIGN KEY(sno) REFERENCES S(sno) ON DELETE CASCADE,
    FOREIGN KEY(cno) REFERENCES C(cno) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DELIMITER //
CREATE TRIGGER grade_trigger
BEFORE
UPDATE ON SC
FOR EACH ROW
BEGIN
    IF NEW.grade < 0 THEN
        SET NEW.grade = 0;
    ELSEIF NEW.grade > 100 THEN
        SET NEW.grade = 100;
    END IF;
END;//
